name: Rust Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: linux_x64
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            bin: gcwd
            name: gcwd_linux_x64_${{ github.ref_name }}.tar.gz
          - release_for: macos_arm64
            os: macos-latest
            target: aarch64-apple-darwin
            bin: gcwd
            name: gcwd_macos_arm64_${{ github.ref_name }}.tar.gz

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build binary
        run: |
          rustup target add ${{ matrix.platform.target }}
          cargo build --release --target ${{ matrix.platform.target }} --locked
          tar -czf target/${{ matrix.platform.name }} -C target/${{ matrix.platform.target }}/release ${{ matrix.platform.bin }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.platform.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}